### ISSUE TITLE
Relationship between this package and github.com/awa/go-iap/appstore

### ISSUE THREAD

**Issue by happenslol** [richzw/appstore#21]
It seems like there is significant overlap between this package and github.com/awa/go-iap. @richzw also seems to be a major contributor over there. I'm wondering, which of these 2 modules should I use if I need to parse App Store Server Notifications and call the IAP API?

It seems like `go-iap/appstore` is easier to use since I can decode the JWT claims directly to the `NotificationPayload` type while I have to manually go through the claims (or use `mapstructure`) with this module. However, that module also includes a lot of functionality for other app stores which I don't need.

**Comment by richzw** [comment]
At the first beginning, when the [App Store Server API](https://developer.apple.com/documentation/appstoreserverapi) was introduced in WWDC21, I try to use those apis, and this project comes up as one personal test project. About one years later, the App Store Server API becomes stable, and there is no related feature of App Store Server API in anther project github.com/awa/go-iap. The codes of this project were added into github.com/awa/go-iap under the folder https://github.com/awa/go-iap/tree/master/appstore/api as one feature.

However, there are difference between those projects. In this project, there are the [backoff](https://github.com/richzw/appstore/blob/master/backoff.go), some middleware function like retry and limit in httpClient. Also load certs from apple.com website in [pool.go](https://github.com/richzw/appstore/blob/master/pool.go) .

For your question, 

> which of these 2 modules should I use if I need to parse App Store Server Notifications and call the IAP API?

I think both of those projects do the same. If not only iOS but also some other platform such as googleplay could be used in your side. https://github.com/awa/go-iap could be better choice, since other platforms verification are supported here. However, if only iOS is used in your side, this project could be better.

> It seems like go-iap/appstore is easier to use since I can decode the JWT claims directly to the NotificationPayload type while I have to manually go through the claims (or use mapstructure) with this module. However, that module also includes a lot of functionality for other app stores which I don't need.

IMO, if you only want to decode the notification, you could just copy the `ParseNotificationV2` to your own project, since only the jwt library is used, it just one personal advice. @happenslol

**Comment by happenslol** [comment]
Thanks for the response! I think it makes sense for me to use this module then, since it sounds like it has some more features than `go-iap`.

> IMO, if you only want to decode the notification, you could just copy the ParseNotificationV2 to your own project, since only the jwt library is used, it just one personal advice.

Yeah, that's what I started out doing - However, I noticed that I need to call the API as well, and I'd need to copy a lot of the types too.

Is there a reason why it's not possible to directly decode the JWT into `NotificationPayload` (and the same for transaction and renewal info)? If not, I'd like to open a PR for this module to make that possible.

**Comment by richzw** [comment]
> Is there a reason why it's not possible to directly decode the JWT into NotificationPayload (and the same for transaction and renewal info)? If not, I'd like to open a PR for this module to make that possible.

No, Welcome your PR :smile:  @happenslol
